### PR TITLE
Add bors.toml

### PR DESCRIPTION
**Pull request by nicolasvienot**
Test meilisearch-bors

### CODE REVIEW

**Comment by nicolasvienot** [comment]
bors try

**Comment by nicolasvienot** [comment]
bors try

**Comment by nicolasvienot** [comment]
bors merge

**Comment by nicolasvienot** [comment]
bors merge

**Comment by eskombro** [comment]
borseal ping

**Comment by eskombro** [comment]
Thanks borseal :)

**Pull request merged**
